# Generated by Django 5.2.3 on 2025-06-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_user_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='description',
        ),
    ]
