# Generated by Django 5.2.3 on 2025-07-01 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_task_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tasklist',
            old_name='owner',
            new_name='user',
        ),
    ]
